name: reticfox
channels:
  - conda-forge
  - defaults
dependencies:
  - bottleneck
  - dask
  - gsw
  - netCDF4
  - pip
  - pyngl
  - python>=3.6
  - scipy
  - xarray
  - click
  - pip:
    - globus-cli